spring:
  application:
    name: paralife
  threads:
    virtual:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

paralife:
  world:
    width: 256
    height: 256
